language: generic 
sudo: required
services:
	- docker

before_install:
	- docker build -t dpatel554/docker-react -f Dockerfile.dev .

script:
	- docker run -e CI=true dpatel554/docker-react npm run test